# no use here
n_bits = 5

[grid]
nx = 128             # X方向网格数量
ny = 256             # Y方向网格数量
resolution = 40e-9   # 网格分辨率（单位：米，40纳米）
npml = 20            # 完美匹配层(PML)层数
region_distance = 10 # 工作区域边界距离（网格数）
src_pos = 1          # 光源起始位置（网格坐标）
wg_width = 8         # 波导宽度（网格数）
source_margin = 2    # 光源边缘间距

[dataset]
n_bits = 5
input = "./dataset/5bit/input.npy"
output = "./dataset/5bit/output.npy"

[[layers]]
[layers.input]
n_bits = 10 # 输入端口比特数
[layers.output]
n_bits = 8 # 输出端口比特数

[[layers]]
[layers.input]
n_bits = 8 # 输入端口比特数
[layers.output]
n_bits = 5 # 输出端口比特数

[basic]
epsilon_min = 1.0  # 最小介电常数（空气）
epsilon_max = 12.0 # 最大介电常数（硅）
freq = 200e12      # 工作频率（200THz）
kernel_radius = 2  # 卷积核半径（网格数）
alpha = 3e5        # 优化目标函数权重系数
beta = 0.5         # 材料密度插值参数
proj_beta = 100.0  # 投影参数β（控制陡度）
proj_eta = 0.5     # 投影参数η（阈值位置）
num_proj = 1       # 投影操作次数
num_conv = 1       # 卷积操作次数
E0_scale = 1     # Ez0的缩放因子

[train]
step_size = 0.003     # 优化步长
test_batch_size = 32  # 测试批次大小
train_batch_size = 32 # 训练批次大小 
num_epochs = 100      # 训练轮数
penalty_factor = 1.25 # 惩罚因子（用于约束违反）

[save_load]
viz_freq = 10
test_freq = 2
save_path = "./models"                                 # 保存和加载模型的路径
load_path = "./models/Thu Mar  6 21:06:39 2025/98.npy" # 加载模型的路径
